# Sonarr Configuration
sonarr:
  instances:
    - label: tv # label must be a unique value from other labels
      server:
        addr: 
        port: 8989 # Default is 8989
        path: / # Default is /. If set, it must start and finish with /. Eg: /radarr/
        ssl: false # Default false
      auth:
        apikey: 
        username: 
        password: 
      search: true # Start search after adding series
      seasonFolder: true
      excludedRootFolders:# If set must not have a trailing slash Eg: /mnt/Media
        - # First excluded folder, add others with a "-" on a new line (same indentation)
      narrowRootFolderNames: true # If true, only the last folder name will be shown instead of full path
      excludedQualityProfiles:
        - # First excluded quality profile, add others with a "-" on a new line (same indentation)
      defaultTags:
        - addarr
      addRequesterIdTag: true # Add telegram user id as tag on series
      adminRestrictions: false

    # - label: tv_4k # label must be a unique value from other labels
    #   server:
    #     addr: 
    #     port: 8980
    #     path: / # Default is /. If set, it must start and finish with /. Eg: /radarr/
    #     ssl: false # Default false
    #   auth:
    #     apikey: 
    #     username: 
    #     password: 
    #   search: true # Start search after adding series
    #   seasonFolder: true
    #   excludedRootFolders:# If set must not have a trailing slash Eg: /mnt/Media
    #     - # First excluded folder, add others with a "-" on a new line (same indentation)
    #   narrowRootFolderNames: true # If true, only the last folder name will be shown instead of full path
    #   excludedQualityProfiles:
    #     - # First excluded quality profile, add others with a "-" on a new line (same indentation)
    #   defaultTags:
    #     - addarr
    #   addRequesterIdTag: true # Add telegram user id as tag on series
    #   adminRestrictions: false

# Radarr Configuration
radarr:
  instances:
    - label: movies # label must be a unique value from other labels
      server:
        addr: 
        port: 7878 # Default is 7878
        path: / # Default is /. If set, it must start and finish with /. Eg: /radarr/
        ssl: false # Default false
      auth:
        apikey: 
        username: 
        password: 
      search: true # Start search after adding series
      minimumAvailability: announced
      excludedRootFolders: # If set must not have a trailing slash Eg: /mnt/Media
        - # First excluded folder, add others with a "-" on a new line (same indentation)
      narrowRootFolderNames: true # If true, only the last folder name will be shown instead of full path
      excludedQualityProfiles:
        - 
      defaultTags:
        - addarr
      addRequesterIdTag: true # Add telegram user id as tag on movies
      adminRestrictions: false

    # - label: movies_4k # label must be a unique value from other labels
    #   server:
    #     addr: 
    #     port: 7870
    #     path: / # Default is /. If set, it must start and finish with /. Eg: /radarr/
    #     ssl: false # Default false
    #   auth:
    #     apikey: 
    #     username: 
    #     password: 
    #   search: true # Start search after adding series
    #   minimumAvailability: announced
    #   excludedRootFolders: # If set must not have a trailing slash Eg: /mnt/Media
    #     - # First excluded folder, add others with a "-" on a new line (same indentation)
    #   narrowRootFolderNames: true # If true, only the last folder name will be shown instead of full path
    #   excludedQualityProfiles:
    #     - 
    #   defaultTags:
    #     - addarr
    #   addRequesterIdTag: true # Add telegram user id as tag on movies
    #   adminRestrictions: false
  
# Telegram Configuration
telegram:
  token:
  password:

# Transmission Configuration
transmission:
  enable: false # Enable the Transmission commands
  onlyAdmin: true # Transmission command  will only work for admins
  host: # IP-adress of the Transmission service
  authentication: true # Is Transmission protected with a password?
  username: 
  password:

# Sabnzbd Configuration
sabnzbd:
  enable: false
  onlyAdmin: true
  server:
    addr:
    port: 8090 # Default is 8090
    path: / # Default is / . If set, it must start and finish with / . Eg: /sabnzbd/
    ssl: false # Default false
  auth:
    apikey:
    username:
    password:

# qBittorrent Configuration
qbittorrent:
  enable: false
  onlyAdmin: true
  server:
    addr: 
    port: 8080 # Default is 8080
    path: / # Default is / . If set, it must start and finish with / . Eg: /qbittorrent/
    ssl: false # Default false
  auth:
    username: 
    password: 

# Optional settings:
## Language
language: en-us # de-de, en-us, es-es, fr-fr, it-it, nl-be, pl-pl, pt-pt, ru-ru

## Entrypoints
entrypointAuth: auth # auth or a custom entrypoint
entrypointHelp: help # help entrypoint
entrypointAdd: start # start or a custom entrypoint
entrypointAllSeries: allSeries # allSeries or a custom entrypoint
entrypointAllMovies: allMovies # allMovies or a custom entrypoint
entrypointTransmission: transmission # transmission or a custom entrypoint
entrypointSabnzbd: sabnzbd # sabnzbd or a custom entrypoint
entrypointqBittorrent: qbittorrent # qbittorrent or a custom entrypoint

## Restrict some commands to only admins and/or provide extra authorization by usernames
enableAdmin: false # Check admin.txt
enableAllowlist: false # Check allowlist.txt - very restrictive!

## Logging
logToConsole: true
debugLogging: false
adminNotifyId:
